# version: "3.9"
version: "3.3"

services:
  perlite:
    image: sec77/perlite:latest
    container_name: obsidian_backend_dev
    environment:
      # - NOTES_PATH=Demo
      - NOTES_PATH=paranoiawhy
      - LINE_BREAKS=true
      - HIDE_FOLDERS=docs,private,trash,Attachments
    volumes:
      - ./perlite:/var/www/perlite
      # - ./perlite/Demo:/var/www/perlite/Demo:ro
      - ./perlite/paranoiawhy:/var/www/perlite/paranoiawhy:ro

  web:
    build:
        context: ./web
    image: sec77/perlite_web:stable
    container_name: obsidian_web_dev
    ports:
      - 80:80
      # - 1234:1234
    volumes:
      - ./perlite:/var/www/perlite
      - ./perlite/Demo:/var/www/perlite/Demo:ro
    depends_on:
      - perlite

