name: Docker Image CI

on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["dev"]

jobs:
  build:
    runs-on: ubuntu-latest
    # https://stackoverflow.com/questions/67023441/deploy-docker-container-with-compose-github-actions
    defaults:
      run:
        working-directory: ./web

    steps:
      # - uses: actions/checkout@v3
      # - name: Build the Docker image
      #   run: docker build . --file Dockerfile --tag paranoiawhy_obsidian:$(date +%s)

      # https://docs.github.com/en/actions/publishing-packages/publishing-docker-images#publishing-images-to-docker-hub
      - name: Check out the repo
        uses: actions/checkout@v3

      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: paranoiawhy/obsidian
          tags: latest

      - name: Build and push Docker images
        id: docker_build
        uses: docker/build-push-action@v2.3.0
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          # tags: |
          #   ${{env.VERSION_TAG}}
          #   ${{env.LASTEST_TAG}}
          # build-args: |
          #   ${{steps.version_step.outputs.version}}
